[package]
name = "sumer9999dev/react-tooltips"
description = "https://github.com/SUMER9999dev/React-Tooltips"
version = "1.0.0"
authors = ["SUMER <Discord: sumer_real>", "Tesmi <Discord: tesmi>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json", "README.md", "LICENSE"]

[dependencies]
react = "jsdotlua/react@17.1.0"
react-roblox = "jsdotlua/react-roblox@17.1.0"
